# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
os:
  - linux
  - osx
compiler:
  - clang
  - gcc

matrix:
  exclude:
  - os: osx
    compiler: clang

branches:
  only:
  - master

env:
  - NOT_CRAN=true

r_github_packages:
  - jimhester/covr
r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - ggplot2
  - pbapply
  - testthat
  - roxygen2
  - devtools

after_success:
  - Rscript -e 'covr::codecov()'
