# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - os: osx
    compiler: clang
    r: release
    env: SHLIB_OPENMP_CFLAGS=""
    env: SHLIB_OPENMP_CXXFLAGS=""
branches:
  only:
  - master

env:
  - NOT_CRAN=true

r_github_packages:
  - jimhester/covr
r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - ggplot2
  - pbapply
  - testthat
  - roxygen2
  - devtools

after_success:
  - Rscript -e 'covr::codecov()'
