# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
# safelist
branches:
  only:
  - master

env:
  - NOT_CRAN=true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
